### ISSUE TITLE
Implement encrypted (private) repositories

### ISSUE THREAD

**Issue by sembrestels** [pandonetwork/pando#32]
Keybase already [have a solution](https://keybase.io/blog/encrypted-git-for-everyone) for encrypted git repos. Maybe you can use it!

**Comment by osarrouy** [comment]
Hey !

That’s something we have in mind indeed but the tricky part is the decentralized infrastructure for key management ... :)

**Comment by osarrouy** [comment]
Closing for now since it's far away on the feature list :)
