### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by deamme** [pandonetwork/pando#34]
I made partly a custom tab navigation before but aragonUI has been updated and includes a more intentional API now.

We should use the new API. https://github.com/aragon/aragon-ui/releases/tag/v0.32.0

**Comment by osarrouy** [comment]
I think the navigation should handle at least 4 different tabs:

**Overview**. Description of the repo + display of the readme [if it exists] + some basic usage stats in the future. Also display a placeholder text if the repo is empty

**Code**. Code browsing interface as we already have + the ability to navigate through commits.

**Pull Requests**. Browse PR + offer the ability to diff files.

**Lineage Requests**. Browse open LR + past lineage minting (à la Token Manager)

**Comment by DaniellMesquita** [comment]
Implemented in 7e201ec8c533872bf260b226701c21bd782bbdca
