### ISSUE TITLE
Improve code highlighting

### ISSUE THREAD

**Issue by deamme** [pandonetwork/pando#35]
Right now we are using https://github.com/FormidableLabs/prism-react-renderer to do code highlighting but we don't switch "highlighting modes" depending on file type. We have discussed that we should make a mapping of file extension to supported languages.

Languages supported in `prism-react-renderer`:
https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

**Comment by DaniellMesquita** [comment]
Commit 244294994eb79da4896ac0d70ff3e14c41916045
