### ISSUE TITLE
Why Pando?

### ISSUE THREAD

**Issue by yeqbfgxjiq** [pandonetwork/pando#52]
Please forgive me if I'm a little too obtuse to connect the dots, but the [Why Pando?](https://github.com/pandonetwork/pando#why-pando-) section doesn't satisfy my curiosities. It does talk about a really cool tree/root system, which is lit. It does not tell me why this project specifically is named after that awesome tree/root system. More clarity would be appreciated :)

Also, super cool logo! 

Also, now that I think about it... the picture helps: the roots are the code and files, and those support the ecosystem of applications that users live in and interact with. This was not immediately obvious though, so please make it more explicit lol (if that is indeed the message/goal of the project, otherwise please correct me!)

**Comment by osarrouy** [comment]
Hey @burrrata,

Got you. We're going pretty fast on the explanation and it would make sense to clarify those.

Gonna update the readme soon :)

**Comment by osarrouy** [comment]
Merged in #57.
