### ISSUE TITLE
[Question] Is it possible to have a .tar.gz file as repo, but version inside it?

### ISSUE THREAD

**Issue by danimesq** [pandonetwork/pando#55]
Not good to version a binary, but its inner contents.

I know doubts and laughs will spawn from the question "have only a .tar.gz as repo", but reading [about USV](http://usv.js.org/) you could understand.

**Comment by danimesq** [comment]
Dat Protocol is open for implementing that:
http://web.archive.org/web/20190510180052/https://github.com/datproject/dat/issues/1107

**Comment by osarrouy** [comment]
The current pando release rely on git so unfortunately we can't implement features which are not support by git ... :( So closing for now :)
